name: Parallel_Workflow
on:
  push:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Statement1
        run: echo "Hello GitHub Actions!"

      - name: Printing Statement2
        run: echo "Good Evening!"

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Statement3
        run: echo "Welcome to GitHub-Actions"

      - name: Printing Statement4
        run: echo "Classes are going good"
